### ISSUE TITLE
Merge is deprecated in latest version of keras i got import error

### ISSUE THREAD

**Issue by outofdata** [rupak-118/Quora-Question-Pairs#2]
Traceback (most recent call last):
  File "test.py", line 33, in <module>
    from keras.layers import LSTM, Embedding, Input, Merge
ImportError: cannot import name 'Merge'

error at line no.33 and 239

**Comment by rupak-118** [comment]
Yes. Seems like Merge is deprecated in the latest Keras versions.
Instead the alternative is to either use "merge", which is function taking tensors as inputs and is a wrapper around the old Merge. It's used as part of the functional API.
For custom function modes like this one, a Lambda layer can also be used.

**Comment by pru007** [comment]
Hi, did you resolve this issue? Else can you explain how to use merge -functional API

,Thanks in advance

**Comment by Donnamaddy** [comment]
Do changes...!!
Thanks in advance

**Comment by pru007** [comment]
Yeah, I just used Lambda layer and it worked fine..

-Thank you

**Comment by mithun-0** [comment]
How to solve this when using `Lambda` instead of `Merge`.
`
TypeError: __init__() missing 1 required positional argument: 'function'`
@pru007 @rupak-118
